### ISSUE TITLE
Zoom out in Android Browser

### ISSUE THREAD

**Issue by NicholasRBowers** [NicholasRBowers/CSS-Slider-Menu#1]
When the menu is visible in an Android browser (at least), and the user zooms out, it breaks the layout.  The layout can be fixed by toggling back to the collapsed view or by moving the elements around.  I'd like the layout to look a lot more solid.

**Comment by stefanvermaas** [comment]
Isn't this fixed by setting the viewport to not scrollable?

**Comment by NicholasRBowers** [comment]
No.  Once you do set it to not scrollable, it doesn't allow you to zoom in, but it still lets you zoom out when the menu is showing (because the effective width of the #page is now 150%)..  I'm still trying to find a way to get around the issue.  Does this happen in mobile safari as well?

**Comment by stefanvermaas** [comment]
Got your version somewhere online? 

Thought it didn't happen, but not sure now. I've used a container to set an overflow, that might work.

**Comment by NicholasRBowers** [comment]
The URL for my online version is http://www.woodysenterprises.com/other/CSS-Menu-Slider.html - it is a little out of date right now, but I'll be updating it soon.  I think you'll be able to see the zoom out bug if you look at it though.  Does it not happen with your version?

**Comment by stefanvermaas** [comment]
These are the things on iOS:

Safari: 
- Nothing happens, because the label approach doesn't work without the fix.

Chrome:
- Works partly. The menu slides out, but it's not possible to slide back. 

In my version everything works fine, on Safari and on Chrome. So my issues are for Android and yours are for iOS :). The zoom bug doesn't occur at any of our versions on both Chrome and Safari.

**Comment by NicholasRBowers** [comment]
Here's what I got so far for testing (Chrome doesn't work on my phone's ROM, I have to wait to use my rooted Kindle fire with Chrome on it):

Your version:
Default Android browser - Label press doesn't work.
Firefox - Works perfectly, no bugs.
Dolphin Browser - Label press doesn't work.
Opera - Works perfectly, no bugs, pretty laggy though.

My version:
Default Android Browser - Obvious layout issue, header is the only thing that displays.
Dolphin Browser - Works as expected, zoom-out bug still present, content div still horizontally scrollable.
Firefox - Works as expected, transitions are choppy (content div) or non-existent (fixed elements), the header doesn't stay pinned to the top of the page, instead scrolls with the page, and then resets, no zoom out bug, content div is still horizontally scrollable.
Opera - Works as expected, scrollbars visible in the navigation menu, and nav does not extend to 100% height, no zoom out bug, but fixed elements aren't smooth and show up anywhere on the page (you can open the menu, and then swipe right to go to the content area, and the menu will follow you if you don't close it.

Interesting errors..  I'm going to have to do some thinking to tighten up this design..

**Comment by stefanvermaas** [comment]
You got nice stuff there in America. I've never heard of the Dolphin browser and never seen a Kindle Fire (don't have those in Europe..).

And I think the mine caused that little issues because I've not used fixed and absolute positioning. Those positions can give the most strange layout errors. 

There're a lot of browsers out there for android, I really hoping those don't come to iOS to.. Those versions are always way buggier than the desktop versions and you need to think about them..

**Comment by NicholasRBowers** [comment]
I actually spent four months in London when I was studying abroad, and I definitely agree with you!  The technology just wasn't there.  Maybe it was just where I was staying, but the dryers didn't even dry our clothes, we had to hang them out - which is almost unheard of here..  I do like the way your cell phone networks are set up though - everything is unlocked/off of license..  Here, if you want the newest phone, you have to sign a two-year contract, and you can only upgrade once every two years (unless you can afford to spend $600 or $700 on a phone).  I digress.

The position stuff in CSS definitely causes more errors than I'd like to admit :/  I'm thinking about fixing the header and nav menu, but making everything else float: left - perhaps that will yield better behavior.  As for the expected behavior, do you think that the nav menu should partially cover up the content div, or should it push it off screen like it does now?  I think that if we just make it cover it up, it may fix that zoom bug I'm having, but I'm not sure how nice that would look.

I don't wish there were less browsers, I wish that there were less rendering engines, and that the rendering engines yielded similar results..  I also wish that older browsers could utilize the newest rendering engines automatically, so browsers became just a skin to view the engines, and even if people didn't update their browsers, we wouldn't still have to design for IE6!

**Comment by NicholasRBowers** [comment]
Think I may have fixed by setting overflow-x: hidden on the body tag.  Will test and verify after I work out all the kinks I've created.
